---
- name: install postgres packages
  apt: pkg={{item}} update_cache=yes
  with_items:
      - postgresql-{{pgversion}}
      - postgresql-{{pgversion}}-postgis-2.1
      - postgresql-server-dev-{{pgversion}}
- name: install psycopg2 package
  apt: pkg=python-psycopg2 update_cache=yes
- name: create postgres user
  postgresql_user: name={{dbuser}} password={{dbpassword}} role_attr_flags=SUPERUSER state=present
  sudo_user: postgres
- name: create postgres database
  postgresql_db: name={{dbname}} owner={{dbuser}}
  sudo_user: postgres
  notify:
    - load extensions
- name: allow password login
  lineinfile: dest=/etc/postgresql/{{pgversion}}/main/pg_hba.conf line="host all all 0.0.0.0/0 md5"
  sudo_user: postgres
  notify:
    - restart postgres
- name: listen on all ports
  lineinfile: dest=/etc/postgresql/{{pgversion}}/main/postgresql.conf line="listen_addresses='*'"
  sudo_user: postgres
  notify:
    - restart postgres
