---
- name: install node and npm
  apt: pkg={{item}} update_cache=yes
  with_items:
    - node
    - npm
- name: install npm packages
  npm: name={{item}} state=present global=yes
  with_items: npm_packages
- name: update to latest
  npm: name={{item}} state=latest global=yes
  with_items: npm_packages
- name: Find path to nodejs
  command: which nodejs
  register: nodejs_path
- name: symlink nodejs to node
  file: src={{item}} dest=/usr/sbin/node state=link
  with_items: nodejs_path.stdout
