---
# install python packages (using facts)
- name: setup django python 2 variables
  set_fact: uwsgi_pkg=uwsgi-plugin-python
  when: python_version == 2
- name: setup django python 3 variables
  set_fact:wsgi_pkg=uwsgi-plugin-python3
  when: python_version == 3
- name: install needed packages
  apt: pkg={{item}} update_cache=yes
  with_items:
    - uwsgi
    - nginx

# uwsgi and nginx
- name: write uwsgi template
  template: src=uwsgi.j2 dest=/etc/uwsgi/apps-enabled/{{project_name}}.ini
  notify:
    - restart uwsgi
- name: remove nginx sites-enabled/default
  file: path=/etc/nginx/sites-enabled/default state=absent
- name: write nginx template
  template: src=nginx.j2 dest=/etc/nginx/sites-enabled/{{project_name}}
  notify:
    - restart nginx

# setup code handled by django-base
